name: CI for Interrogator

# on: [push, pull_request]

on:
  push:     
    branches:
      - main
  pull_request: 
    types: [opened, synchronize, reopened, closed]
    
env:
  BUILD_TYPE: Release
#   ACTIONS_RUNNER_DEBUG: true
#   ACTIONS_STEP_DEBUG: true


jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy: 
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-latest]
        # os: [ubuntu-20.04, ubuntu-18.04, windows-2019, macos-10.15]
        # version: ['5.9.0', '5.15.1', '6.2.0']
        version: ['5.9.0']

        # Ubuntu 18 is not a supported target for Qt 6: https://www.qt.io/blog/qt6-development-hosts-and-targets
        exclude:
          - os: ubuntu-18.04
            version: '6.2.0'
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        if: startsWith(matrix.os, 'mac')
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{matrix.version}}
          host: mac
          target: 'desktop'
          # arch: 'win64_mingw73'
          dir: '${{github.workspace}}/qt/'
          install-deps: 'true'

      - name: Install Qt
        if: startsWith(matrix.os, 'windows')
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{matrix.version}}
          host: windows
          target: 'desktop'
          # arch: 'win64_mingw73'
          dir: '${{github.workspace}}/qt/'
          install-deps: 'true'
          
      - name: Install Qt
        if: startsWith(matrix.os, 'ubuntu')
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{matrix.version}}
          host: linux
          target: 'desktop'
          # arch: 'win64_mingw73'
          dir: '${{github.workspace}}/qt/'
          install-deps: 'true'

      - name: Configure test project on windows
        if: startsWith(matrix.os, 'windows')
        env:
          QT_VERSION: ${{ matrix.version }}
        run: |
          cd tests/TestWithModules
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          IF "%QT_VERSION:~0,1%"=="5" ( dir %Qt5_DIR%\lib\cmake ) ELSE ( dir %Qt6_DIR%\lib\cmake )
          qmake
        shell: cmd

      - name: Build
        if: startsWith(matrix.os, 'windows')
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
        working-directory: ${{github.workspace}}
        run:  |
              qmake CONFIG+=release
              mingw32-make -f Makefile.Release all -platform win32-g++
              dir '${{github.workspace}}'

      - name: Upload Artifact
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v3
        with:
          name: Interrogator ${{github.os}}
          path: |
            Interrogator.exe
    
      - name: Create build foder 
        if: (!startsWith(matrix.os, 'windows'))
        run: mkdir ${{github.workspace}}/build
        
        
      - name: Build
        if: startsWith(matrix.os, 'ubuntu')
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
        working-directory: ${{github.workspace}}
        run:  |
              qmake CONFIG+=release
              make
              ls -R
              
      - name: Upload Artifact ${{github.os}}
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v3
        with:
          name: Interrogator ${{github.os}}
          path: |
            Interrogator
              
      - name: Build
        if: startsWith(matrix.os, 'mac')
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
        working-directory: ${{github.workspace}}
        run:  |
              qmake CONFIG+=release
              make

      - name: Tar files
        if: startsWith(matrix.os, 'mac')
        run: tar -cvf interrogator.tar Interrogator.app

      - name: Upload Artifact ${{github.os}}
        if: startsWith(matrix.os, 'mac')
        uses: actions/upload-artifact@v3
        with:
          name: Interrogator ${{github.os}}
          path: |
            interrogator.tar 
            


